version: '2'

services:
  mielemqtt:
    environment:
      TZ: "Europe/Berlin"
    hostname: mielemqtt
    image: pharndt/mielemqtt
    volumes:
     - ./config:/var/lib/miele-to-mqtt-gw:ro
    restart: always 
