name: Build release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        working-directory: app
        shell: bash
        run: npm install

      - name: Build
        working-directory: app
        shell: bash
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker container and push
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          RELEASE_VERSION: 0.0.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            breiti78/mielemqtt:latest
